### PR TITLE
support PyPI

### PR DESCRIPTION
**Pull request by acgtyrant**
I change the `setup.py` so that it supports PyPI.

By the way, I have upload this package to PyPI already.

### CODE REVIEW

**Comment by mcordts** [comment]
Thank you for the PR. I decided to merge a related one: https://github.com/mcordts/cityscapesScripts/pull/31
Is that sufficient for you, or do you wish to update this PR?

**Comment by acgtyrant** [comment]
Sufficient. If you would like to own the PyPI package, tell me you username and I transfer it to you.

**Comment by acgtyrant** [comment]
Of I destroy the PyPI package, and you upload the new package by your merged setup.py instead.

**Comment by mcordts** [comment]
@acgtyrant would you mind transferring the pypi package to me? Username is mcordts

**Comment by acgtyrant** [comment]
OK.

**Comment by mcordts** [comment]
Can you try to login to pypi and then add my username here:
https://pypi.python.org/pypi?:action=role_form&package_name=cityscapesScripts

**Comment by mcordts** [comment]
@acgtyrant  I believe that you can transfer ownership by Logging in to pypi, click "Manage Project", click "Collaborators" and add me as "Owner".

**Comment by acgtyrant** [comment]
@mcordts Done.

**Comment by mcordts** [comment]
Great, thank you. That worked. 
Would you mind doing the same for https://test.pypi.org/?

**Comment by acgtyrant** [comment]
Done. Could you remove me from collaborators?

**Comment by mcordts** [comment]
Done. Thanks again.

**Pull request closed without merging**
